import type { Metadata } from "next";
import "@/style/globals.css";
import clsx from "clsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  className,
  children,
}: {
  className: string;
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx("p-2", className)}>{children}</body>
    </html>
  );
}
